spring:
  application:
    name: tiendahibridabackend
  datasource:
    url: jdbc:mysql://localhost:3306/ucompensarshop?useSSL=false&serverTimezone=UTC
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

security:
    jwt:
        secret: mysecretkey
        expiration: 3600000 # 1 hour in milliseconds
        issuer: tienda-hibrida