spring:
  application:
    name: tiendahibridabackend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ucompensarshop}?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8081}

security:
  jwt:
    secret: ${JWT_SECRET:mysecretkey}
    expiration: 3600000
    issuer: tienda-hibrida
