spring:
  application:
    name: tiendahibridabackend
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:mysecretkey}
    expiration: 3600000
    issuer: tienda-hibrida
